---
- name: check iptables+ipsets Playbook
  hosts: all
  tasks:
    - name: check iptables+ipsets Task
      script: files/view.sh
      register: results
      
    - debug: var=results.stdout_lines
